services:
  bot:
    build:
      context: .
      target: runtime
    image: my-tg-bot:latest
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /opt/my_tg_bot/data:/app/data
